services:
  # PostgreSQL database for our services
  database:
    build: 
      context: ./backend-database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend-database/.env

  # MLFlow server for experiment tracking (uses the database)
  experiment-tracking:
    build: ./backend-service-experiment-tracking
    ports:
      - 5000:5000
    depends_on:
      - database

  train-dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  # prefect server
  orchestration:
    build: ./backend-service-orchestration
    ports:
      - 4200:4200

volumes:
  # storage for persistent database usage
  postgres-data: