services:
  # PostgreSQL database for our services
  backend-database:
    build:
      context: ./backend-database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend-database/.env

  # MLFlow server for experiment tracking (uses the database)
  experiment-tracking:
    build: ./backend-service-experiment-tracking
    ports:
      - 5000:5000
    depends_on:
      - backend-database

  train-dev:
    #might need to add extra dockerfile => look lab 9 compose
    build: ./train-dev
    # image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    depends_on:
      - experiment-tracking
      - orchestration

  # prefect server
  orchestration:
    build: ./backend-service-orchestration
    ports:
      - 4200:4200

  #API service for frontend
  frontend-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  # batch service for data processing => TO BE ADDED
  batch-service:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  # default login: admin/admin
  #grafana:
  #  image: grafana/grafana
  #  restart: unless-stopped
  #  volumes:
  #    - grafana-data-config-datasources:/etc/grafana/provisioning/datasources:ro
  #    - grafana-data-config-dashboards:/etc/grafana/provisioning/dashboards:ro
  #    - grafana-data-dashboards:/opt/grafana/dashboards
  #    - batch-data:/batch-data
  #  ports:
  #    - "3400:3000"
  #  networks:
  #    - mlops-network

volumes:
  # storage for persistent database usage
  postgres-data:
  # storage for batch-data
  batch-data:
  # grafana volumes for persistent configuration and datastorage
  grafana-data-config-datasources:
  grafana-data-config-dashboards:
  grafana-data-dashboards: