apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: backend-database:5432
    user: postgres
    database: batch_db
    isDefault: true
    editable: true
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"